          run: |
            # 1. Установка инструментов
            dnf install -y rpm-build rpmdevtools git wget ncurses-devel hmaccalc zstd openssl-devel bison flex elfutils-libelf-devel dwarves perl-devel python3-devel gcc make patch diffutils
            
            cd /work
            # 2. Клонируем с GitHub (зеркало), чтобы избежать ошибки 403
            git clone --depth 1 https://github.com -b 6.18-xanmod linux-xanmod
            cd linux-xanmod
            
            # 3. Конфигурация под i5-6200U (Skylake)
            make defconfig
            scripts/config --enable CONFIG_X86_64_VERSION_3
            scripts/config --set-str CONFIG_X86_64_VERSION_3_NAME "v3"
            scripts/config --enable CONFIG_DRM_I915
            scripts/config --module CONFIG_DRM_NOUVEAU
            make olddefconfig
            
            # 4. Сборка RPM (ядро, devel, headers)
            make binrpm-pkg -j$(nproc)
            
            # 5. Копируем результат
            cp /root/rpmbuild/RPMS/x86_64/*.rpm /work/
